### PR TITLE
[SeaTunnel #884] Fix NullPointerException caused by engine type

### LINKED ISSUE #884: [Bug] [Config] The script option `-t` cause NullPointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The script option `-t` will cause NullPointerException
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:197)
	at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:69)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:55)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:29)
```

### SeaTunnel Version

branch dev

### SeaTunnel Config

```conf
env {
    spark.app.name="seatunnel"
}
source {
  Fake {
    result_table_name = "my_dataset"
  }
}

transform {
}

sink {
  Console {}
}


```

### Running Command

```shell
./bin/start-seatunnel-spark.sh -c /app/seatunnel-2.x/config/demo.conf -e client -m local -i app=test
```

### Error Exception

```log
The script option `-t` cause NullPointerException,because of Engine.NULL
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
closes #884
Need to create Spark/FlinkEnvironment according to Engine type，but the Engine is null.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by simon824** [comment]
cc @CalvinKirs @leo65535 Thanks.

**Comment by leo65535** [comment]
hi @simon824, I checked the `-t` option as your case, seems we got different Exception.
```
[dcadmin@dcadmin seatunnel-dist-2.0.5-SNAPSHOT-2.11.8]$ ./bin/start-seatunnel-spark.sh -c config/application.conf -e client -m local -i app=test -t

[INFO] spark conf: --conf "spark.app.name=seatunnel"
Warning: Ignoring non-spark config property: "spark.app.name=seatunnel"
2021-12-29 13:29:10 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-12-29 13:29:10 INFO  ConfigBuilder:78 - Loading config file: config/application.conf
2021-12-29 13:29:10 INFO  ConfigBuilder:89 - parsed config file: {
    "env" : {
        "spark.app.name" : "seatunnel"
    },
    "source" : [
        [
                        {
                "plugin_name" : "result_table_name"
            },
            "my_dataset"${app}
,
            "Fake"
        ]
    ],
    "transform" : [],
    "sink" : [
        [
            "Console"
        ]
    ]
}

2021-12-29 13:29:10 ERROR Seatunnel:173 - 

===============================================================================


2021-12-29 13:29:10 ERROR Seatunnel:176 - Fatal Error, 

2021-12-29 13:29:10 ERROR Seatunnel:178 - Please submit issue a bug in https://github.com/InterestingLab/waterdrop/issues

2021-12-29 13:29:10 ERROR Seatunnel:180 - Reason:config/application.conf: 6: source has type list of LIST rather than list of OBJECT 

2021-12-29 13:29:10 ERROR Seatunnel:181 - Exception StackTrace:org.apache.seatunnel.config.ConfigException$WrongType: config/application.conf: 6: source has type list of LIST rather than list of OBJECT
        at org.apache.seatunnel.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:471)
        at org.apache.seatunnel.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:480)
        at org.apache.seatunnel.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:485)
        at org.apache.seatunnel.config.ConfigBuilder.checkIsStreaming(ConfigBuilder.java:102)
        at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:185)
        at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:62)
        at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:92)
        at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:59)
        at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by simon824** [comment]
> hi @simon824, I checked the `-t` option as your case, seems we got different Exception.
> 
> ```
> [dcadmin@dcadmin seatunnel-dist-2.0.5-SNAPSHOT-2.11.8]$ ./bin/start-seatunnel-spark.sh -c config/application.conf -e client -m local -i app=test -t
> 
> [INFO] spark conf: --conf "spark.app.name=seatunnel"
> Warning: Ignoring non-spark config property: "spark.app.name=seatunnel"
> 2021-12-29 13:29:10 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> 2021-12-29 13:29:10 INFO  ConfigBuilder:78 - Loading config file: config/application.conf
> 2021-12-29 13:29:10 INFO  ConfigBuilder:89 - parsed config file: {
>     "env" : {
>         "spark.app.name" : "seatunnel"
>     },
>     "source" : [
>         [
>                         {
>                 "plugin_name" : "result_table_name"
>             },
>             "my_dataset"${app}
> ,
>             "Fake"
>         ]
>     ],
>     "transform" : [],
>     "sink" : [
>         [
>             "Console"
>         ]
>     ]
> }
> 
> 2021-12-29 13:29:10 ERROR Seatunnel:173 - 
> 
> ===============================================================================
> 
> 
> 2021-12-29 13:29:10 ERROR Seatunnel:176 - Fatal Error, 
> 
> 2021-12-29 13:29:10 ERROR Seatunnel:178 - Please submit issue a bug in https://github.com/InterestingLab/waterdrop/issues
> 
> 2021-12-29 13:29:10 ERROR Seatunnel:180 - Reason:config/application.conf: 6: source has type list of LIST rather than list of OBJECT 
> 
> 2021-12-29 13:29:10 ERROR Seatunnel:181 - Exception StackTrace:org.apache.seatunnel.config.ConfigException$WrongType: config/application.conf: 6: source has type list of LIST rather than list of OBJECT
>         at org.apache.seatunnel.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:471)
>         at org.apache.seatunnel.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:480)
>         at org.apache.seatunnel.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:485)
>         at org.apache.seatunnel.config.ConfigBuilder.checkIsStreaming(ConfigBuilder.java:102)
>         at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:185)
>         at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:62)
>         at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:92)
>         at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:59)
>         at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:29)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
>         at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
>         at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
>         at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
>         at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
>         at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
>         at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
>         at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> ```

Your case looks like the config was parsing failed, try this one.
```
env {
    spark.app.name="seatunnel"
}
source {
  Fake {
    result_table_name = "my_dataset"
  }
}
}
transform {
  sql {
    table_name = "user_view"
    sql = ${?table_name}"select * from user_view where city = '"${?sql}"'"
  }
}
sink {
  Console {}
}
}

```

**Comment by leo65535** [comment]
hi @simon824, here is the lstest result
```
[dcadmin@dcadmin seatunnel-dist-2.0.5-SNAPSHOT-2.11.8]$ vi config/application.conf 
[dcadmin@dcadmin seatunnel-dist-2.0.5-SNAPSHOT-2.11.8]$ ./bin/start-seatunnel-spark.sh -c config/application.conf -e client -m local -i app=test -t

[INFO] spark conf: --conf "spark.app.name=seatunnel"
Warning: Ignoring non-spark config property: "spark.app.name=seatunnel"
2021-12-29 15:31:55 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-12-29 15:31:55 INFO  ConfigBuilder:78 - Loading config file: config/application.conf
2021-12-29 15:31:55 INFO  ConfigBuilder:89 - parsed config file: {
    "env" : {
        "spark.app.name" : "seatunnel"
    },
    "source" : [
        {
            "result_table_name" : "my_dataset",
            "plugin_name" : "Fake"
        }
    ],
    "transform" : [
        {
            "plugin_name" : "sql",
            "table_name" : "user_view",
            "sql" : ${?table_name}"select * from user_view where city = '"${?sql}"'"
        }
    ],
    "sink" : [
        {
            "plugin_name" : "Console"
        }
    ]
}

2021-12-29 15:31:55 INFO  SparkContext:54 - Running Spark version 2.4.0
2021-12-29 15:31:55 INFO  SparkContext:54 - Submitted application: seatunnel
2021-12-29 15:31:55 INFO  SecurityManager:54 - Changing view acls to: dcadmin
2021-12-29 15:31:55 INFO  SecurityManager:54 - Changing modify acls to: dcadmin
2021-12-29 15:31:55 INFO  SecurityManager:54 - Changing view acls groups to: 
2021-12-29 15:31:55 INFO  SecurityManager:54 - Changing modify acls groups to: 
2021-12-29 15:31:55 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(dcadmin); groups with view permissions: Set(); users  with modify permissions: Set(dcadmin); groups with modify permissions: Set()
2021-12-29 15:31:56 INFO  Utils:54 - Successfully started service 'sparkDriver' on port 44517.
2021-12-29 15:31:56 INFO  SparkEnv:54 - Registering MapOutputTracker
2021-12-29 15:31:56 INFO  SparkEnv:54 - Registering BlockManagerMaster
2021-12-29 15:31:56 INFO  BlockManagerMasterEndpoint:54 - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2021-12-29 15:31:56 INFO  BlockManagerMasterEndpoint:54 - BlockManagerMasterEndpoint up
2021-12-29 15:31:56 INFO  DiskBlockManager:54 - Created local directory at /tmp/blockmgr-9bc23ab1-2048-4316-a7ca-fd88799ab719
2021-12-29 15:31:56 INFO  MemoryStore:54 - MemoryStore started with capacity 366.3 MB
2021-12-29 15:31:56 INFO  SparkEnv:54 - Registering OutputCommitCoordinator
2021-12-29 15:31:56 INFO  log:192 - Logging initialized @3512ms
2021-12-29 15:31:56 INFO  Server:351 - jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
2021-12-29 15:31:56 INFO  Server:419 - Started @3615ms
2021-12-29 15:31:56 INFO  AbstractConnector:278 - Started ServerConnector@6079cf5{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2021-12-29 15:31:56 INFO  Utils:54 - Successfully started service 'SparkUI' on port 4040.
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6edaa77a{/jobs,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@749f539e{/jobs/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5ca1f591{/jobs/job,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6ef81f31{/jobs/job/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6075b2d3{/stages,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@33abde31{/stages/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@997d532{/stages/stage,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7a18e8d{/stages/stage/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3028e50e{/stages/pool,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5560bcdf{/stages/pool/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@b558294{/storage,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@bb095{/storage/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@777c350f{/storage/rdd,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@27aae97b{/storage/rdd/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4c9e38{/environment,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5d1e09bc{/environment/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4bdc8b5d{/executors,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3bcd426c{/executors/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5f14a673{/executors/threadDump,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@726a17c4{/executors/threadDump/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5dc3fcb7{/static,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6b3871d6{/,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@37095ded{/api,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7923f5b3{/jobs/job/kill,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6b63d445{/stages/stage/kill,null,AVAILABLE,@Spark}
2021-12-29 15:31:56 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://dcadmin.work:4040
2021-12-29 15:31:56 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-flink.jar at spark://dcadmin.work:44517/jars/seatunnel-core-flink.jar with timestamp 1640763116838
2021-12-29 15:31:56 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-spark.jar at spark://dcadmin.work:44517/jars/seatunnel-core-spark.jar with timestamp 1640763116839
2021-12-29 15:31:56 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-sql-2.0.5-SNAPSHOT-2.11.8.jar at spark://dcadmin.work:44517/jars/seatunnel-core-sql-2.0.5-SNAPSHOT-2.11.8.jar with timestamp 1640763116840
2021-12-29 15:31:56 WARN  SparkContext:66 - The jar file:/work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-spark.jar has been added already. Overwriting of added jars is not supported in the current version.
2021-12-29 15:31:56 INFO  Executor:54 - Starting executor ID driver on host localhost
2021-12-29 15:31:57 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40581.
2021-12-29 15:31:57 INFO  NettyBlockTransferService:54 - Server created on dcadmin.work:40581
2021-12-29 15:31:57 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2021-12-29 15:31:57 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, dcadmin.work, 40581, None)
2021-12-29 15:31:57 INFO  BlockManagerMasterEndpoint:54 - Registering block manager dcadmin.work:40581 with 366.3 MB RAM, BlockManagerId(driver, dcadmin.work, 40581, None)
2021-12-29 15:31:57 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, dcadmin.work, 40581, None)
2021-12-29 15:31:57 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, dcadmin.work, 40581, None)
2021-12-29 15:31:57 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@77a2aa4a{/metrics/json,null,AVAILABLE,@Spark}
2021-12-29 15:31:57 WARN  StreamingContext:66 - spark.master should be set as local[n], n > 1 in local mode if you have receivers to get data, otherwise Spark jobs will not get resources to process the received data.
2021-12-29 15:31:57 ERROR Seatunnel:114 - Plugin[org.apache.seatunnel.spark.transform.Sql] contains invalid config, error: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigConcatenation(${?table_name}"select * from user_view where city = '"${?sql}"'") 

2021-12-29 15:31:57 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2021-12-29 15:31:57 INFO  AbstractConnector:318 - Stopped Spark@6079cf5{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2021-12-29 15:31:57 INFO  SparkUI:54 - Stopped Spark web UI at http://dcadmin.work:4040
2021-12-29 15:31:57 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2021-12-29 15:31:57 INFO  MemoryStore:54 - MemoryStore cleared
2021-12-29 15:31:57 INFO  BlockManager:54 - BlockManager stopped
2021-12-29 15:31:57 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped
2021-12-29 15:31:57 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2021-12-29 15:31:57 INFO  SparkContext:54 - Successfully stopped SparkContext
2021-12-29 15:31:57 INFO  ShutdownHookManager:54 - Shutdown hook called
2021-12-29 15:31:57 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-3f3ab240-66f9-4ab3-baad-050542b74e86
2021-12-29 15:31:57 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-4231815e-59e3-49fe-a258-7d41780e030f
```

**Comment by simon824** [comment]
@leo65535 Sorry it's my fault, still because of the configuration file I provided is abnormal, try this again, Thx.

```
env {
    spark.app.name="seatunnel"
}
source {
  Fake {
    result_table_name = "my_dataset"
  }
}

transform {
}

sink {
  Console {}
}
```

**Comment by leo65535** [comment]
Every things are ok, seatunnel version: dev

```
[dcadmin@dcadmin seatunnel-dist-2.0.5-SNAPSHOT-2.11.8]$ ./bin/start-seatunnel-spark.sh -c config/application.conf -e client -m local -i app=test -t

[INFO] spark conf: --conf "spark.app.name=seatunnel"
Warning: Ignoring non-spark config property: "spark.app.name=seatunnel"
2021-12-29 15:59:34 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-12-29 15:59:34 INFO  ConfigBuilder:78 - Loading config file: config/application.conf
2021-12-29 15:59:34 INFO  ConfigBuilder:89 - parsed config file: {
    "env" : {
        "spark.app.name" : "seatunnel"
    },
    "source" : [
        {
            "result_table_name" : "my_dataset",
            "plugin_name" : "Fake"
        }
    ],
    "transform" : [],
    "sink" : [
        {
            "plugin_name" : "Console"
        }
    ]
}

2021-12-29 15:59:34 INFO  SparkContext:54 - Running Spark version 2.4.0
2021-12-29 15:59:34 INFO  SparkContext:54 - Submitted application: seatunnel
2021-12-29 15:59:34 INFO  SecurityManager:54 - Changing view acls to: dcadmin
2021-12-29 15:59:34 INFO  SecurityManager:54 - Changing modify acls to: dcadmin
2021-12-29 15:59:34 INFO  SecurityManager:54 - Changing view acls groups to: 
2021-12-29 15:59:34 INFO  SecurityManager:54 - Changing modify acls groups to: 
2021-12-29 15:59:34 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(dcadmin); groups with view permissions: Set(); users  with modify permissions: Set(dcadmin); groups with modify permissions: Set()
2021-12-29 15:59:34 INFO  Utils:54 - Successfully started service 'sparkDriver' on port 42057.
2021-12-29 15:59:34 INFO  SparkEnv:54 - Registering MapOutputTracker
2021-12-29 15:59:34 INFO  SparkEnv:54 - Registering BlockManagerMaster
2021-12-29 15:59:34 INFO  BlockManagerMasterEndpoint:54 - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2021-12-29 15:59:34 INFO  BlockManagerMasterEndpoint:54 - BlockManagerMasterEndpoint up
2021-12-29 15:59:34 INFO  DiskBlockManager:54 - Created local directory at /tmp/blockmgr-4e1490d8-b4ae-498c-a5cf-b12c73e844ea
2021-12-29 15:59:34 INFO  MemoryStore:54 - MemoryStore started with capacity 366.3 MB
2021-12-29 15:59:34 INFO  SparkEnv:54 - Registering OutputCommitCoordinator
2021-12-29 15:59:34 INFO  log:192 - Logging initialized @4579ms
2021-12-29 15:59:35 INFO  Server:351 - jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
2021-12-29 15:59:35 INFO  Server:419 - Started @4726ms
2021-12-29 15:59:35 INFO  AbstractConnector:278 - Started ServerConnector@72ed9aad{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2021-12-29 15:59:35 INFO  Utils:54 - Successfully started service 'SparkUI' on port 4040.
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@50825a02{/jobs,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5f84abe8{/jobs/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4650a407{/jobs/job,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6a4d7f76{/jobs/job/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@10ec523c{/stages,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@53dfacba{/stages/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@79767781{/stages/stage,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@245a060f{/stages/stage/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6edaa77a{/stages/pool,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@1e63d216{/stages/pool/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@62ddd21b{/storage,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@16c3ca31{/storage/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2d195ee4{/storage/rdd,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2d6aca33{/storage/rdd/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@21ab988f{/environment,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@29314cc9{/environment/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4e38d975{/executors,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@35f8a9d3{/executors/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@48ea2003{/executors/threadDump,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6b1e7ad3{/executors/threadDump/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@63e5e5b4{/static,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6a969fb8{/,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7a18e8d{/api,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@bb095{/jobs/job/kill,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@777c350f{/stages/stage/kill,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://dcadmin.work:4040
2021-12-29 15:59:35 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-flink.jar at spark://dcadmin.work:42057/jars/seatunnel-core-flink.jar with timestamp 1640764775331
2021-12-29 15:59:35 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-spark.jar at spark://dcadmin.work:42057/jars/seatunnel-core-spark.jar with timestamp 1640764775331
2021-12-29 15:59:35 INFO  SparkContext:54 - Added JAR file:///work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-sql-2.0.5-SNAPSHOT-2.11.8.jar at spark://dcadmin.work:42057/jars/seatunnel-core-sql-2.0.5-SNAPSHOT-2.11.8.jar with timestamp 1640764775332
2021-12-29 15:59:35 WARN  SparkContext:66 - The jar file:/work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-spark.jar has been added already. Overwriting of added jars is not supported in the current version.
2021-12-29 15:59:35 INFO  Executor:54 - Starting executor ID driver on host localhost
2021-12-29 15:59:35 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44739.
2021-12-29 15:59:35 INFO  NettyBlockTransferService:54 - Server created on dcadmin.work:44739
2021-12-29 15:59:35 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2021-12-29 15:59:35 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, dcadmin.work, 44739, None)
2021-12-29 15:59:35 INFO  BlockManagerMasterEndpoint:54 - Registering block manager dcadmin.work:44739 with 366.3 MB RAM, BlockManagerId(driver, dcadmin.work, 44739, None)
2021-12-29 15:59:35 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, dcadmin.work, 44739, None)
2021-12-29 15:59:35 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, dcadmin.work, 44739, None)
2021-12-29 15:59:35 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3f1ddac2{/metrics/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:35 WARN  StreamingContext:66 - spark.master should be set as local[n], n > 1 in local mode if you have receivers to get data, otherwise Spark jobs will not get resources to process the received data.
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -           *********                              ##############                                                              ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -          *#########                              ##############                                                              ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#***  ****                                    ##                                                                    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#*                                            ##                                                                    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#*                                            ##                                                                    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#*             ********     ********          ##         ##       ##    ## *******     ## *******      ********     ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#*            **#######*    ########*         ##         ##       ##    ##*######**    ##*######**    **#######*    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         *#****        **#*** *****   **** ***#*        ##         ##       ##    ###******#*    ###******#*   **#*** *****   ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -          *###*****    *#*      *#*          *#*        ##         ##       ##    ##*     *#*    ##*     *#*   *#*      *#*   ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -           ***####**   *#*      *#*          *#*        ##         ##       ##    ##*     *#*    ##*     *#*   *#*      *#*   ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -              ****##*  *#******###*   *****####*        ##         ##       ##    ##       ##    ##       ##   *#******###*   ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -                  *#*  *###########  **#########        ##         ##       ##    ##       ##    ##       ##   *###########   ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -                  *#*  *#*           *#****   ##        ##         ##       ##    ##       ##    ##       ##   *#*            ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -                  *#*  *#*           *#*     *##        ##         *#*     *##    ##       ##    ##       ##   *#*            ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -                  *#*  *#**          *#*     *##        ##         *#*     *##    ##       ##    ##       ##   *#**           ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         ***** ****#*  **#*** ****   *#** ***###        ##         *#*** **###    ##       ##    ##       ##   **#*** ****    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         ##########*    **########   **######*##        ##         **######*##    ##       ##    ##       ##    **########    ##                 
2021-12-29 15:59:36 INFO  AsciiArtUtils:57 -         **********      ****#****    ******* ##        ##          ******* ##    ##       ##    ##       ##     ****#****    ##                 
2021-12-29 15:59:37 INFO  SharedState:54 - Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/spark-warehouse').
2021-12-29 15:59:37 INFO  SharedState:54 - Warehouse path is 'file:/work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/spark-warehouse'.
2021-12-29 15:59:37 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3fde8f7c{/SQL,null,AVAILABLE,@Spark}
2021-12-29 15:59:37 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@11d86b9d{/SQL/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:37 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@800d065{/SQL/execution,null,AVAILABLE,@Spark}
2021-12-29 15:59:37 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@691124ee{/SQL/execution/json,null,AVAILABLE,@Spark}
2021-12-29 15:59:37 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4293e066{/static/sql,null,AVAILABLE,@Spark}
2021-12-29 15:59:38 INFO  StateStoreCoordinatorRef:54 - Registered StateStoreCoordinator endpoint
2021-12-29 15:59:38 INFO  CodeGenerator:54 - Code generated in 186.677462 ms
2021-12-29 15:59:39 INFO  CodeGenerator:54 - Code generated in 9.829865 ms
2021-12-29 15:59:39 INFO  CodeGenerator:54 - Code generated in 9.030868 ms
+------------------+
|raw_message       |
+------------------+
|Hello garyelephant|
|Hello rickyhuo    |
|Hello kid-xiong   |
+------------------+

2021-12-29 15:59:39 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2021-12-29 15:59:39 INFO  AbstractConnector:318 - Stopped Spark@72ed9aad{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2021-12-29 15:59:39 INFO  SparkUI:54 - Stopped Spark web UI at http://dcadmin.work:4040
2021-12-29 15:59:39 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2021-12-29 15:59:39 INFO  MemoryStore:54 - MemoryStore cleared
2021-12-29 15:59:39 INFO  BlockManager:54 - BlockManager stopped
2021-12-29 15:59:39 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped
2021-12-29 15:59:39 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2021-12-29 15:59:39 INFO  SparkContext:54 - Successfully stopped SparkContext
2021-12-29 15:59:39 INFO  ShutdownHookManager:54 - Shutdown hook called
2021-12-29 15:59:39 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-f25a7304-fcb9-4bb3-8d39-63b2f8b737d8
2021-12-29 15:59:39 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-c5ba55c4-8635-4a5a-9d18-781eb8e78f6b

```

File: seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandSparkArgs.java [hunk 1]
```diff
@@ -43,7 +43,7 @@
 
     @Parameter(names = {"-t", "--check"},
         description = "check config")
-    private boolean testConfig = true;
+    private boolean testConfig = false;
```
Comment (simon824) [inline seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandSparkArgs.java:46]: Fixed the default value of `check config`, please review this again when free, thx. @leo65535

Comment (leo65535) [reply seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandSparkArgs.java:46]: thanks, will check the patch today again.

**Comment by kezhenxu94** [comment]
Hey @simon824 , I can see this exception in seatunnel-core-flink but this patch doesn't seem to resolve it, anything I missed?

**Comment by simon824** [comment]
> Hey @simon824 , I can see this exception in seatunnel-core-flink but this patch doesn't seem to resolve it, anything I missed?

Updated, thanks a lot for your feedback, please test again when free, thx.

**Review by kezhenxu94 — APPROVED** [review]
> > Hey @simon824 , I can see this exception in seatunnel-core-flink but this patch doesn't seem to resolve it, anything I missed?
> 
> Updated, thanks a lot for your feedback, please test again when free, thx.

LGTM now, @leo65535 please recheck

**Comment by kezhenxu94** [comment]
I've added this https://github.com/apache/incubator-seatunnel/pull/901to verify the basic functions of seatunnel-spark, which should expose this kind of errors earlier, but I'm investigating some ways to do the same verification for seatunnel-flink...

**Review by leo65535 — APPROVED** [review]
👍
